[grid]
nx = 1600
nz = 1600
dx = 10.0
dz = 10.0

[materials]
vp  = 3000.0
vs  = 1732.0
rho = 2700.0

[simulation]
total_time = 5.0
cfl_safety = 0.5

[[sources]]
x         = 200
z         = 1000
amplitude = 25.0
frequency = 20.0

[[sources]]
x         = 500
z         = 200
amplitude = 5.0
frequency = 20.0

[[sources]]
x         = 1000
z         = 900
amplitude = 15.0
frequency = 20.0

[visualization]
field        = "vmag"
video_length = 25.0
fps          = 30.0
iteration    = 1
image_width  = 1200
image_height = 1000
